### ISSUE TITLE
Enemies are able to kill you through the floor

### ISSUE THREAD

**Issue by XOCX404** [xntkrnl/WiderShipMod#2]
Enemies like the Mimic and Bracken can grab you through the floor when using mods like lethal escape, this does not happen in the vanilla ship

**Comment by xntkrnl** [comment]
Hello, I am aware of this issue and am working on a solution.

**Comment by xntkrnl** [comment]
Hello, I inform you that this problem will be fixed in the next patch. Thank you for reporting this problem.

**Comment by XOCX404** [comment]
Thank you for your hard work!!
