### ISSUE TITLE
WiderShip breaks TooManySuits' suit rack

### ISSUE THREAD

**Issue by thaatds233** [xntkrnl/WiderShipMod#3]
The TooManySuits mod adds pages to the suit rack and this mod breaks that feature.

**Comment by xntkrnl** [comment]
Hi, in the last update I added the ability to change the wall (beams, solid wall, no wall) and, as far as I remember, the mod was supposed to work with one of these modes. Of course, this is not a fix (it was not planned at that time). I can advise you to contact the developer of the TooManySuits mod or use https://thunderstore.io/c/lethal-company/p/darmuh/suitsTerminal/ instead.

**Comment by xntkrnl** [comment]
Since there have been no new complaints about this issue, I am closing this thread.
