### ISSUE TITLE
Regarding whether it is possible to add configurations that allow players to disable the left and right spaceship extension settings

### ISSUE THREAD

**Issue by 1450143535** [xntkrnl/WiderShipMod#5]
Dear spaceship extension author, hello, I am a player of Lethal Company. First of all, thank you very much for your creation on spaceship extension. But recently while playing, I have also discovered some drawbacks of this mod. I hope the author can give me a timely reply and suggestion. In the new external map of Artifical, if the left side of the spaceship is expanded, it will make it inconvenient for employees to board the spaceship on the left side. Therefore, I would like to try to turn off the left side expansion and only keep the right side expansion, but there are no relevant settings in the configuration. I hope the mod author can adopt this suggestion（In fact, on some maps, the expansion on the left side of the spaceship can have a certain degree of impact on the player's ability to return to the spaceship and be restricted）

**Comment by xntkrnl** [comment]
Hi, the option to switch between only left/only right/both parts will be coming in the future. As for the ladders, I think I will move them closer to the door.

**Comment by xntkrnl** [comment]
1.3.0 is out, an option has been added to the config
