### ISSUE TITLE
Serious error issue!!

### ISSUE THREAD

**Issue by lenmon666** [xntkrnl/WiderShipMod#6]
As long as you install this mod, whether it's the old version or the latest 1.2.5 version, if you choose to load the map, the console will display this error message!
Both third-party map mods and official maps may have this issue!
Moreover, as long as this problem occurs, it is a frequent and large-scale refresh of error messages!
At the same time, it will cause a large amount of logs to be written to the local disk, which can lead to intermittent lag problems in the game!
Can you investigate this issue and provide a fix and update
The screenshot of the error message is the one below! Below, all the configuration information of the module in r2z format is also uploaded as a package
![222](https://github.com/user-attachments/assets/bbb0b848-c18d-4040-b5f4-3984e696ea67)
[Default_1727824024171.zip](https://github.com/user-attachments/files/17217539/Default_1727824024171.zip)

**Comment by xntkrnl** [comment]
Hi, I've found this error since 1.2.1, and I know it's either a hoarder bug (more likely) or a spider, but I don't know why. If this error occurs in 1.1.0, then I have nothing to do with it (I think). By the way, if you have performance issues with console log spamming, I recommend using AsyncLoggers.

**Comment by xntkrnl** [comment]
I read about this error on the Unity forums. This error occurs when a mob spawns and tries to walk on the navmesh. I don't change the interior navmesh in any way (only the ship, but in such a way that the values ​​inside the navmesh components don't change and it doesn't interfere with the mobs), so the problem isn't in the mod, but in the game.
