### ISSUE TITLE
deprecated dependency #1

### ISSUE THREAD

**Issue by WhoPlaysTheFool** [xntkrnl/WiderShipMod#8]
Thunderstore page lists [Matty Fixes Experimental](https://thunderstore.io/c/lethal-company/p/mattymatty/Matty_Fixes_Experimental/) as a dependency, and as of today this mod is marked as deprecated.
I presume this is due to all functions in this mod being added to the stable release, [Matty Fixes](https://thunderstore.io/c/lethal-company/p/mattymatty/Matty_Fixes/)

It may be worthwhile to push a minor update to Thunderstore to swap dependency

**Comment by xntkrnl** [comment]
Hi, thanks for the feedback.
I was informed about this a couple of hours ago, but I can't change the dependency right now. However, I will change it as soon as I can.

**Comment by WhoPlaysTheFool** [comment]
closing as Matty Fixes Experimental is no longer marked as deprecated, and seems to not cause any issues
